In [1]:
import numpy as np

In [3]:
arr = np.arange(11)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [4]:
np.sqrt(arr)

array([ 0.        ,  1.        ,  1.41421356,  1.73205081,  2.        ,
        2.23606798,  2.44948974,  2.64575131,  2.82842712,  3.        ,
        3.16227766])

In [5]:
np.exp(arr)

array([  1.00000000e+00,   2.71828183e+00,   7.38905610e+00,
         2.00855369e+01,   5.45981500e+01,   1.48413159e+02,
         4.03428793e+02,   1.09663316e+03,   2.98095799e+03,
         8.10308393e+03,   2.20264658e+04])

In [7]:
A = np.random.randn(10)
A

array([-0.32649602, -0.3499818 ,  0.49188109, -0.70376041,  1.28033953,
        0.44682229, -0.983863  , -1.26073895, -0.35056919, -0.13066009])

In [9]:
B = np.random.randn(10)
B

array([-0.70974367, -0.22198353,  1.48971627,  1.19021946, -1.21549575,
        0.32817201,  0.5164776 ,  0.27650541,  0.04677025, -1.26197717])

In [11]:
np.add(A,B)

array([-1.03623969, -0.57196532,  1.98159736,  0.48645905,  0.06484378,
        0.7749943 , -0.4673854 , -0.98423354, -0.30379894, -1.39263726])

In [12]:
np.maximum(A,B)

array([-0.32649602, -0.22198353,  1.48971627,  1.19021946,  1.28033953,
        0.44682229,  0.5164776 ,  0.27650541,  0.04677025, -0.13066009])